version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    expose:
      - 3000
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=boardapp
      - POSTGRES_PORT=5432

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boardapp
    expose:
      - 5432
